// Auto-generated by scripts/fetch_fonts.cjs
export type FontFace = { family: string; weight: number; file: string };
export const FONT_FACES: FontFace[] = [
{ family: 'ZCOOL XiaoWei', weight: 400, file: 'ZCOOLXiaoWei-400-0.ttf' },
{ family: 'Noto Serif SC', weight: 300, file: 'NotoSerifSC-300-0.ttf' },
{ family: 'Noto Serif SC', weight: 400, file: 'NotoSerifSC-400-0.ttf' },
{ family: 'Noto Serif SC', weight: 600, file: 'NotoSerifSC-600-0.ttf' },
];
