#!/usr/bin/env node
// Download only the glyphs needed for the video from Google Fonts.
// Outputs: public/fonts/*.woff2 + public/fonts/fonts.css
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const COPY = [
  "当代年轻人为什么都这么丧",
  "没有人教过我们怎么不动声色地长大",
  "小时候以为努力就会有答案",
  "长大后才发现世界是一个巨大的跑道",
  "我们拼命地跑却只是留在原地",
  "有人告诉我们这是最好的时代",
  "可我们看见的是涨不动的工资和买不起的远方",
  "于是我们学会了躺平学会了说算了",
  "不是不想努力是怕努力之后依然没有回声",
  "我们笑着说太难了笑着笑着眼眶就红了",
  "我们不是放弃了只是把期待轻轻放回了口袋",
  "后来才明白丧不是一种失败",
  "是我们对生活最后的温柔",
  "允许自己慢一点允许期待落空",
  "也允许自己只是普通地活着",
  "不必急着好起来丧一点也没关系",
  "我们只是换了一种方式继续爱着这人间",
  "致我们温柔地与世界相处",
  "壹贰叁肆伍陆柒捌玖",
  "。，、·—《》",
].join("");

const FAMILIES = [
  { name: "ZCOOLXiaoWei", cssFamily: "ZCOOL XiaoWei", weights: [400] },
  { name: "NotoSerifSC", cssFamily: "Noto Serif SC", weights: [300, 400, 600] },
];

const OUT = path.join(__dirname, "..", "public", "fonts");
const CSS_OUT = path.join(__dirname, "..", "src", "fonts.css");
fs.mkdirSync(OUT, { recursive: true });

const curl = (url, out) => {
  execFileSync("curl", ["-sS", "-m", "60", "-L", "-o", out, url], { stdio: "inherit" });
};

const cssRules = [];
let cssText = "";
let tsFaces = "";

for (const fam of FAMILIES) {
  for (const w of fam.weights) {
    const cssUrl =
      "https://fonts.googleapis.com/css2?family=" +
      encodeURIComponent(fam.cssFamily + (w !== 400 ? `:wght@${w}` : "")) +
      "&text=" +
      encodeURIComponent(COPY);
    const css = execFileSync("curl", ["-sS", "-m", "30", cssUrl], { encoding: "utf8" });
    const urls = [...css.matchAll(/url\((https:[^)]+)\)/g)].map((m) => m[1]);
    if (!urls.length) throw new Error(`No font file found for ${fam.name} w${w}`);
    urls.forEach((u, i) => {
      const fname = `${fam.name}-${w}-${i}.ttf`;
      curl(u, path.join(OUT, fname));
      cssText += `@font-face{font-family:'${fam.cssFamily}';font-style:normal;font-weight:${w};font-display:block;src:url("/fonts/${fname}") format('truetype');}\n`;
      tsFaces += `{ family: '${fam.cssFamily}', weight: ${w}, file: '${fname}' },\n`;
    });
    console.log(`${fam.name} w${w}: ${urls.length} subset file(s) downloaded`);
  }
}

fs.writeFileSync(CSS_OUT, cssText);
fs.writeFileSync(
  path.join(__dirname, "..", "src", "fontFaces.ts"),
  `// Auto-generated by scripts/fetch_fonts.cjs\n` +
    `export type FontFace = { family: string; weight: number; file: string };\n` +
    `export const FONT_FACES: FontFace[] = [\n${tsFaces}];\n`
);
console.log("fonts.css + fontFaces.ts written");
